version: '3.9'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
    volumes:
      - mongodb:/misc/db
    ports:
      - '27017:27017'

volumes:
  mongodb:
